workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 20
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Create Android folder
        script: |
          flutter create . --platforms=android --org com.saikrupa --project-name saikrupa_classes
      - name: Get packages
        script: |
          flutter pub get
      - name: Generate Icon
        script: |
          flutter pub run flutter_launcher_icons
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
