name: saikrupa_classes_karad
description: Saikrupa Classes Karad App with Receipt and WhatsApp
publish_to: 'none'
version: 1.0.5+6
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  image_picker: ^1.0.7
  share_plus: ^7.2.1
flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
