name: android
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'
      - run: |
          rm -rf android
          flutter create --platforms=android --org com.saikrupa --project-name saikrupa_classes_karad --overwrite./
      - run: flutter pub get
      - run: flutter build apk --release --no-tree-shake-icons
      - uses: actions/upload-artifact@v4
        with:
          name: Saikrupa-APK
          path: build/app/outputs/flutter-apk/app-release.apk
