name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'
          channel: 'stable'
      - name: Recreate and Fix
        run: |
          rm -rf android
          flutter create . --platforms=android --project-name saikrupa_classes_karad --org com.saikrupa
          # Fix kotlin version
          sed -i "s/ext.kotlin_version.*/ext.kotlin_version = '1.8.22'/" android/build.gradle
          # Add kotlin force at end of app/build.gradle
          echo '
          configurations.all {
              resolutionStrategy {
                  force "org.jetbrains.kotlin:kotlin-stdlib:1.8.22"
                  force "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.22"
                  force "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22"
              }
          }
          ' >> android/app/build.gradle
          flutter pub get
      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
